This directory contains the R code used to generate the results
presented in the article: "Small sample corrections for Wald tests in Latent Variable Models" published in JRSS-C
(https://doi.org/10.1111/rssc.12414). It is organized as follows:
- *the BATCH files* define the simulation studies. Each file was
  excecuted 40 times using a different id (obtain using
  =Sys.getenv("SGE_TASK_ID")= in R) and therefore a different seed
  when randomly generating the data. The output of the simulations
  were saved in a =Results= directory, not uploaded on Github to save
  space but available upon request.  

- *the BUILD file* gather the results of the various simulations by
  reading the data in the =Results= directory. It converts them into a
  small number of table (=data.table= format) and exports them in the
  =Results= directory.
- *the RESULTS files* are used to generate the numbers, figures, and
  tables displayed in the article.


/Example:/ the first run of the file =BATCH_simulation-mixedModel.R=
  exports the results in
  =Results/simulation-mixedModel/estimate-S1.rds=. Running
  =BUILD_simulation= will read all the final results in
  =Results/simulation-mixedModel= (e.g. =estimate-S1.rds= to
  =estimate-S40.rds=) and combine them in a single table. The type 1
  errror rate is then computed and exported in
  =Results/type1error-illustration-mixedModel.rds=. The bias of the
  estimates is also computed and exported in
  =Results/bias-simulation-mixedModel=. The file =RESULTS_figure4.R=
  uses =Results/type1error-illustration-mixedModel.rds= to produce
  figure 4.


* More details on the BATCH files

- =BATCH_simulation-mixedModel.R=, =BATCH_simulation-factorModel.R=,
  and =BATCH_simulation-lvm.R= : these files were used to perform the
  simulations studies in section 7 (respectively, scenario A, B, and
  C). They also contains the code to assess the timing of Algorithm 2
  reported in the discussion.


- =BATCH_illustration-mixedModel.R=,
  =BATCH_illustration-factorModel.R=, =BATCH_illustration-lvm.R= :
  these files contains to the simulation study used to assess the type
  1 error of the latent variable models used in the illustration
  section (respectively, section 9.1, 9.2, and 9.3).

- =BATCH_comparison-ML-IV-GLS.R=: this file was used to assess the
  control of the type 1 error when using Wald test with (uncorrected)
  maximum likelihood estimator and other estimators (IV,GLS,WLS). This
  corresponds to the last paragraph of the discussion and table S4 in
  the supplementary material.

- =BATCH_IV-non-normal.R=, =BATCH_IV-non-normal2.R=,
  =BATCH_IV-non-normal3.R=: these files correspond to additional
  simulations performed to assess the control of type 1 error in
  misspecified models (e.g. residuals non normally distributed,
  misspecified covariance structure). The results are not reported in
  the manuscript but are available upon request.
